### ISSUE TITLE
Portfolio online via github pages

### ISSUE THREAD

**Issue by efoosag** [efoosag/Portfolio-setup-and-mobile-version-skeleton#8]
The link to my portfolio online is :https://efoosag.github.io/Portfolio-setup-and-mobile-version-skeleton/

**Comment by prolajumokeoni** [comment]
Good job deploying your application 👍🏿 
- [ ] Kindly fix conflicts on this repository
- [ ] Currently, your website has a horizontal scroll it would be better to try to fix this too
